/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FRMPLATOS.java
 *
 * Created on 13-jul-2011, 12:44:47
 */
package PCKPRESENTACION;

import PCKDAO.*;
import PCKENTIDADES.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class FRMPLATOS extends javax.swing.JInternalFrame {
  Integer idItm;
    /** Creates new form FRMPLATOS */
    public FRMPLATOS() {
        initComponents();
        mostrarItem();
        mostrardata();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboCategoria = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboTipoItem = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboSubCategoria = new javax.swing.JComboBox();
        txtNomItem = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPlatos = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setClosable(true);
        setTitle("MANTENIMIENTO DE PLATOS");

        cboCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCategoriaItemStateChanged(evt);
            }
        });

        jLabel1.setText("CATEGORIA:");

        jLabel2.setText("TIPO DE ITEM:");

        cboTipoItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTipoItemItemStateChanged(evt);
            }
        });
        cboTipoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoItemActionPerformed(evt);
            }
        });

        jLabel3.setText("SUBCATEGORIA:");

        jLabel4.setText("NOMBRE ITEM:");

        jLabel5.setText("PRECIO:");

        jLabel6.setText("DESCRIPCION:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        tblPlatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_ITEM", "NOMBRE", "CATEGORIA", "SUBCATEGORIA", "PRECIO", "DESCRIPCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPlatos);

        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(25, 25, 25)
                                    .addComponent(cboTipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(33, 33, 33)
                                    .addComponent(cboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(cboSubCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNomItem)
                                    .addComponent(txtPrecio)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(cboTipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNomItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnConsultar)
                    .addComponent(btnModificar))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void mostrarItem() {
        TipoItemDAO oTipoItemDAO = new TipoItemDAO();
        List<TipoItemMenu> tipoItemMenus = oTipoItemDAO.getnombres();
        for (TipoItemMenu oItemMenu : tipoItemMenus) {
            cboTipoItem.addItem(oItemMenu.getNombreTipo());
        }

    }

    void BuscarCat() {
        cboCategoria.removeAllItems();
        String TipoItem = cboTipoItem.getSelectedItem().toString();

        CategoriaDAO ocateg = new CategoriaDAO();
        List<Categoria> categorias = ocateg.getnombres(TipoItem);
        for (Categoria oCategoria : categorias) {

            cboCategoria.addItem(oCategoria.getNombre_cat());
        }
    }

    void BuscarSubCat() {
        cboSubCategoria.removeAllItems();
        String cat = cboCategoria.getSelectedItem().toString();

        SubCategoriaDAO osSubCategoriaDAO = new SubCategoriaDAO();
        List<SubCategoria> subCategorias = osSubCategoriaDAO.getnombres(cat);
        for (SubCategoria osSubCategoria : subCategorias) {
            cboSubCategoria.addItem(osSubCategoria.getNombre_sub());
        }
    }
    private void cboTipoItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTipoItemItemStateChanged
        // TODO add your handling code here:

        BuscarCat();



    }//GEN-LAST:event_cboTipoItemItemStateChanged

    private void cboTipoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoItemActionPerformed
        // TODO add your handling code here:
        // BuscarCat();
    }//GEN-LAST:event_cboTipoItemActionPerformed

    private void cboCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCategoriaItemStateChanged
        // TODO add your handling code here:
        BuscarSubCat();
    }//GEN-LAST:event_cboCategoriaItemStateChanged
    void mostrardata() {

        ItemMenuDAO oItemMenuDAO = new ItemMenuDAO();
        List<ItemMenu> itemMenus = oItemMenuDAO.getAll();
        DefaultTableModel m1 = (DefaultTableModel) tblPlatos.getModel();
        m1.setRowCount(0);
        for (ItemMenu itm : itemMenus) {
            Object[] fila = {itm.getIdItem(), itm.getNombre_item(), itm.getoCategoria().getNombre_cat(), itm.getOsuCategoria().getNombre_sub(), itm.getPrecio(), itm.getDescripcion()};
            m1.addRow(fila);
        }
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        ItemMenu oItemMenu = new ItemMenu();
        Categoria oCategoria = new Categoria();
        SubCategoria oSubCategoria = new SubCategoria();

        oCategoria.setNombre_cat(cboCategoria.getSelectedItem().toString());
        oItemMenu.setoCategoria(oCategoria);

        oSubCategoria.setNombre_sub(cboSubCategoria.getSelectedItem().toString());
        oItemMenu.setOsuCategoria(oSubCategoria);

        oItemMenu.setNombre_item(txtNomItem.getText());
        oItemMenu.setDescripcion(txtDescripcion.getText());
        oItemMenu.setPrecio(Double.parseDouble(txtPrecio.getText()));

        ItemMenuDAO oItemMenuDAO = new ItemMenuDAO();
        if (oItemMenuDAO.insertItem(oItemMenu) == true) {
            JOptionPane.showMessageDialog(null, "ITEM AGREGADO CORRECTAMENTE");
            mostrardata();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
       idItm = Integer.parseInt(JOptionPane.showInputDialog("INGRESE ID DE ITEM"));
        ItemMenuDAO oitMenuDAO = new ItemMenuDAO();
        ItemMenu oItemMenu = new ItemMenu();

        oItemMenu = oitMenuDAO.Buscar_id(idItm);
        txtNomItem.setText(oItemMenu.getNombre_item());
        cboCategoria.setSelectedItem(oItemMenu.getoCategoria().getNombre_cat());
        cboSubCategoria.setSelectedItem(oItemMenu.getOsuCategoria().getNombre_sub());
        txtDescripcion.setText(oItemMenu.getDescripcion());
        txtPrecio.setText("" + oItemMenu.getPrecio());
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
          ItemMenu oItemMenu = new ItemMenu();
        Categoria oCategoria = new Categoria();
        SubCategoria oSubCategoria = new SubCategoria();

        oItemMenu.setIdItem(idItm);
        oCategoria.setNombre_cat(cboCategoria.getSelectedItem().toString());
        oItemMenu.setoCategoria(oCategoria);

        oSubCategoria.setNombre_sub(cboSubCategoria.getSelectedItem().toString());
        oItemMenu.setOsuCategoria(oSubCategoria);

        oItemMenu.setNombre_item(txtNomItem.getText());
        oItemMenu.setDescripcion(txtDescripcion.getText());
        oItemMenu.setPrecio(Double.parseDouble(txtPrecio.getText()));

        ItemMenuDAO oItemMenuDAOX = new ItemMenuDAO();
        if (oItemMenuDAOX.updateItem(oItemMenu) == true) {
            JOptionPane.showMessageDialog(null, "ITEM ACTUALIZADO CORRECTAMENTE");
            mostrardata();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox cboCategoria;
    private javax.swing.JComboBox cboSubCategoria;
    private javax.swing.JComboBox cboTipoItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPlatos;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNomItem;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}





